export enum SCREEN {
  HOME = "HOME",
  DISCOVER = "DISCOVER",
  AUCTION = "AUCTION",
  
  PROFILE = "PROFILE",

  NFT_PROPERTY = "NFT_PROPERTY",
  SELLING_NFT = "SELLING_NFT",
  UP_FOR_AUCTION_NFT = "UP_FOR_AUCTION_NFT",
  WALLET = "WALLET",
}